### ISSUE TITLE
Non-scary variant button code refers to wrong button

### ISSUE THREAD

**Issue by pond** [grgcombs/IntelligentSplitViewController#13]
If defining "YOU_DONT_FEEL_QUEAZY_ABOUT_THIS_BECAUSE_IT_PASSES_THE_APP_STORE" to 0 (or leaving it undefined, or whatever) the code at line 112 of IntelligentSplitViewController.m refers to "rightBarButtonItem". This should be "leftBarButtonItem" (certainly on iOS 5.1; I've not tested it on other versions).

I.e.:

		UIBarButtonItem *button = [[[[[self.viewControllers objectAtIndex:1] 
									  viewControllers] objectAtIndex:0] 
									navigationItem] leftBarButtonItem];

By the way... Very useful class, thanks! It allowed me to put a split view inside a tab bar extremely easily. I don't think it's really breaching the HIG, especially when you consider the sort of split views things like the iPad YouTube app present from a tab (e.g. subscriptions tab with its master-like list of subscriptions on the left, or the view shown after a video is played with the related etc. pane on the right).

**Comment by grgcombs** [comment]
At least in the demo on iOS 8 it's still the rightBarButtonItem
