### ISSUE TITLE
Project won't run with current podspec

### ISSUE THREAD

**Issue by MuscleRumble** [grgcombs/IntelligentSplitViewController#24]
I have no idea what this setting does:

    s.xcconfig     = {
        'ONLY_ACTIVE_ARCH' => 'NO'
    }

But it messes up my project. :/ I get a bunch of linker errors and I have no clue why. Deleting this from Pods' xcconfig (and letting "Build Active Architecture Only" for "Debug" to YES as before) fixes it. Do you know why that is or can you explain why you have set this?

Thanks!

**Comment by grgcombs** [comment]
Closed via 1b96db1

**Comment by grgcombs** [comment]
The setting was a left-over from another project -- I'd copied over the pod-spec and didn't remove that before publishing here.
