### ISSUE TITLE
Strange behaviours with the barButtonItem

### ISSUE THREAD

**Issue by timfazio** [grgcombs/IntelligentSplitViewController#3]
Thanks for the wonderful class! It has saved my life.

I noted a strange issue with the barButtonItem, sometimes it would appear slightly to the right, and then stay visible in portrait mode.

I changed your line to this:

```
YOU_DO_FEEL_QUEAZY_AND_FOR_SOME_REASON_YOU_PREFER_THE_LESSER_EVIL_____FRIGHTENING_STUFF
        UIBarButtonItem *button = [[[[[self.viewControllers objectAtIndex:0] 
                                      viewControllers] objectAtIndex:0] 
                                    navigationItem] rightBarButtonItem];
```

This fixed it visually.

An exception does get called when rotating other views, as follows:

```
There was a nasty error while notifyng splitviewcontrollers of an orientation change: *** -[NSMutableArray insertObject:atIndex:]: attempt to insert nil object at 0
```

But it works a treat! 

Cheers

**Comment by kalyan4** [comment]
My task is to change tabbar iem position change according to user criteria my if-condition not perfectly working at this point
CGPoint touchlocation;
[pan locationInView:self.view];

if (tabbarview == nil) {
    tabbarview =[tbItems objectAtIndex:self.tabBarController.selectedIndex];
    [self.tabBarController.view addSubview:tabbarview];
}
if (fixedPos == 0) {
    fixedPos=touchlocation.y;

}[tabbarview removeFromSuperview];
tabbarview.center = touchlocation;

if (pan.state == UIGestureRecognizerStateEnded) {
    // [tabbarview removefromsuperview]
    [tabbarview removeFromSuperview];
    tabbarview =nil;
    fixedPos = 0;

    if(touchlocation.x<4){

        if (touchlocation.x<=109)
        {
            [tbItems exchangeObjectAtIndex:0 withObjectAtIndex:self.tabBarController.selectedIndex];
            NSMutableArray *tvcs=[[self.tabBarController viewControllers]mutableCopy];
            id tempvc=[tvcs objectAtIndex:self.tabBarController.selectedIndex];
            [tvcs removeObject:tempvc];
            [tvcs insertObject:tempvc atIndex:1];
            [self.tabBarController setViewControllers:tvcs animated:YES];

        }else
        if (touchlocation.x>109 && touchlocation.x<=215)
        {
            [tbItems exchangeObjectAtIndex:1 withObjectAtIndex:self.tabBarController.selectedIndex];
            NSMutableArray *tvcs=[[self.tabBarController viewControllers]mutableCopy];
            id tempvc=[tvcs objectAtIndex:self.tabBarController.selectedIndex];
            [tvcs removeObject:tempvc];
            [tvcs insertObject:tempvc atIndex:2];
            [self.tabBarController setViewControllers:tvcs animated:YES];

        }else if (touchlocation.x>215 )
        {
            [tbItems exchangeObjectAtIndex:2 withObjectAtIndex:self.tabBarController.selectedIndex];
            NSMutableArray *tvcs=[[self.tabBarController viewControllers]mutableCopy];
            id tempvc=[tvcs objectAtIndex:self.tabBarController.selectedIndex];
            [tvcs removeObject:tempvc];
            [tvcs insertObject:tempvc atIndex:3];
            [self.tabBarController setViewControllers:tvcs animated:YES];

        }else
        {
            [tbItems exchangeObjectAtIndex:3 withObjectAtIndex:4];
            NSMutableArray *tvcs=[[self.tabBarController viewControllers]mutableCopy];
            id tempvc=[tvcs objectAtIndex:self.tabBarController.selectedIndex];
            [tvcs removeObject:tempvc];
            [tvcs insertObject:tempvc atIndex:4];
            [self.tabBarController setViewControllers:tvcs animated:YES];
        }


    }else
    {
        [tbItems exchangeObjectAtIndex:3 withObjectAtIndex:4];
        NSMutableArray *tvcs=[[self.tabBarController viewControllers]mutableCopy];
        id tempvc=[tvcs objectAtIndex:self.tabBarController.selectedIndex];
        [tvcs removeObject:tempvc];
        [tvcs insertObject:tempvc atIndex:4];
        [self.tabBarController setViewControllers:tvcs animated:YES];
    }
}

**Comment by grgcombs** [comment]
Ok @kalyan4 this doesn't have anything to do with the IntelligentSplitViewController, but rather with Apple's UITabBarController. 

I will say that if you're using static pixel/point offsets and locations, there's probably something wrong with the implementation. I think StackOverflow probably has some snippet hacks to get the CGRect of your UITabBarItem at runtime if that's really what you want.
